version: '3'

services:
  app:
    build: .
    container_name: hotels_app
    depends_on:
      - db
    entrypoint: /docker-entrypoint-api.sh
    ports:
      - "8000:8000"
    environment:
      DB_URL: postgresql://postgres@db:5432/hotels

  db:
    image: postgres:alpine
    container_name: hotels_db
    environment:
      POSTGRES_DB: hotels
    volumes:
      - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data:
